# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\brent\OneDrive\Documents\untitled1\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from housing_visualization.gui.Map import Map


class Ui_mapgui(object):
    def setupUi(self, mapgui):
        mapgui.setObjectName("mapgui")
        mapgui.resize(1085, 919)
        self.centralwidget = QtWidgets.QWidget(mapgui)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 500))
        self.widget.setObjectName("widget")
        self.mapping = Map()
        self.mapping.center_changed.connect(self.update_lat_lon_text)
        self.mapping.clim_changed.connect(self.update_clim)
        self.verticalLayout.addWidget(self.mapping)

        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_2.addWidget(self.horizontalSlider)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(200, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(75, 15))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(200, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setMaximumSize(QtCore.QSize(120, 15))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_4.addWidget(self.checkBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        mapgui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mapgui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1085, 21))
        self.menubar.setObjectName("menubar")
        mapgui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mapgui)
        self.statusbar.setObjectName("statusbar")
        mapgui.setStatusBar(self.statusbar)

        self.horizontalSlider.setMinimum(0)
        self.horizontalSlider.setMaximum(len(self.mapping.dates)-1)
        self.horizontalSlider.valueChanged.connect(self.update_from_slider)
        self.horizontalSlider.valueChanged.connect(self.update_date)

        self.comboBox.addItems(self.mapping.dates)
        self.comboBox.currentIndexChanged.connect(self.update_date_from_combobox)
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.comboBox_2.currentIndexChanged.connect(self.change_colorbar_mode)

        self.checkBox.toggled.connect(self.show_zipcodes)
        self.lineEdit_4.editingFinished.connect(self.update_clim_val)
        self.lineEdit.editingFinished.connect(self.update_clim_val)
        self.lineEdit_2.editingFinished.connect(self.update_lon)
        self.lineEdit_3.editingFinished.connect(self.update_lat)
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        mapgui.setCentralWidget(self.centralwidget)

        self.retranslateUi(mapgui)
        self.mapping.update_plot()

        QtCore.QMetaObject.connectSlotsByName(mapgui)

    def update_from_slider(self, slider_val):
        """Updates the date while the slider is being moved"""
        self.comboBox.setCurrentIndex(slider_val)

    def update_date_from_combobox(self):
        self.horizontalSlider.setValue(self.comboBox.currentIndex())
        self.update_date()

    def update_date(self):
        """Updates the Map date if the slider is released"""
        self.mapping.update_date_by_idx(self.horizontalSlider.value())
        # self.mapping.update_plot()

    def update_lat_lon_text(self, value):
        """Updates the text of lat lon if the map is dragged"""
        self.lineEdit_3.setText("{:.6f}".format(value[1]))
        self.lineEdit_2.setText("{:.6f}".format(value[0]))

    def change_colorbar_mode(self):
        if self.comboBox_2.currentIndex() == 0:
            self.mapping.color_bar_auto_range = True
        else:
            self.mapping.color_bar_auto_range = False

        self.mapping.do_update = True

    def update_clim(self, value):
        self.lineEdit_4.setText("{}".format(value[0]))
        self.lineEdit.setText("{}".format(value[1]))

    def update_clim_val(self):
        color_axis = (float(self.lineEdit_4.displayText()), float(self.lineEdit.displayText()))
        self.mapping.color_axis = color_axis
        self.mapping.do_update = True

    def update_lat(self):
        """Updates the Map latitude if manually changed"""
        value = float(self.lineEdit_3.displayText())

        # Bounds check on the United States, silently fall back to the old center on failure for now
        if value <= 18.91619 or value >= 71.35776:
            self.lineEdit_3.setText("{:.6f}".format(self.mapping.center[1]))
            return

        self.mapping.center = [self.mapping.center[0], value]
        self.mapping.do_update = True

    def update_lon(self):
        """Updates the Map longitude if manually changed"""
        value = float(self.lineEdit_2.displayText())

        # Bounds check on the United States, silently fall back to the old center on failure for now
        if value <= -171.79111 or value >= -66.96466:
            self.lineEdit_2.setText("{:.6f}".format(self.mapping.center[0]))
            return

        self.mapping.center = [value, self.mapping.center[1]]
        self.mapping.do_update = True

    def show_zipcodes(self):
        """Changes the Map value to show zip codes"""
        self.mapping.show_zip_codes = self.checkBox.isChecked()
        self.mapping.do_update = True

    def retranslateUi(self, mapgui):
        _translate = QtCore.QCoreApplication.translate
        mapgui.setWindowTitle(_translate("mapgui", "Housing Prices"))
        self.label_2.setText(_translate("mapgui", self.mapping.dates[0]))
        self.label.setText(_translate("mapgui", self.mapping.dates[-1]))
        self.label_3.setText(_translate("mapgui", "Current Date: "))
        self.comboBox.setCurrentIndex(self.comboBox.findText(str(self.mapping.cur_date)))
        self.label_4.setText(_translate("mapgui", "Latitude | Longitude"))
        self.lineEdit_3.setText("{:.6f}".format(self.mapping.center[1]))
        self.lineEdit_2.setText("{:.6f}".format(self.mapping.center[0]))
        self.horizontalSlider.setValue(self.horizontalSlider.maximum())
        self.checkBox.setText(_translate("mapgui", "Show Labels"))
        self.comboBox_2.setItemText(0, _translate("mapgui", "Auto-scaling Color Bar"))
        self.comboBox_2.setItemText(1, _translate("mapgui", "Static Color Bar"))
        self.label_5.setText(_translate("mapgui", "Color Bar Minimum"))
        self.label_6.setText(_translate("mapgui", "Color Bar Maximum"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    sys._excepthook = sys.excepthook


    def exception_hook(exctype, value, traceback):
        print(exctype, value, traceback)
        sys._excepthook(exctype, value, traceback)
        sys.exit(1)


    sys.excepthook = exception_hook

    mapgui = QtWidgets.QMainWindow()
    ui = Ui_mapgui()
    ui.setupUi(mapgui)
    mapgui.show()
    sys.exit(app.exec_())
