# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\brent\OneDrive\Documents\untitled1\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from housing_visualization.gui.Map import Map


class Ui_mapgui(object):
    def setupUi(self, mapgui):
        mapgui.setObjectName("mapgui")
        mapgui.resize(882, 702)
        self.centralwidget = QtWidgets.QWidget(mapgui)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 761, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget.setObjectName("widget")
        self.mapping = Map()
        self.mapping.center_changed.connect(self.update_lat_lon)
        self.verticalLayout.addWidget(self.mapping)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 500, 761, 82))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalSlider = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setMinimum(0)
        self.horizontalSlider.setMaximum(len(self.mapping.dates)-1)
        self.horizontalSlider.valueChanged.connect(self.update_from_slider)
        self.horizontalSlider.sliderReleased.connect(self.update_date)

        self.verticalLayout_2.addWidget(self.horizontalSlider)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setMinimumSize(QtCore.QSize(200, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setMinimumSize(QtCore.QSize(50, 0))
        self.label_3.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setMinimumSize(QtCore.QSize(200, 0))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        mapgui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mapgui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 882, 21))
        self.menubar.setObjectName("menubar")
        mapgui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mapgui)
        self.statusbar.setObjectName("statusbar")
        mapgui.setStatusBar(self.statusbar)

        self.retranslateUi(mapgui)
        QtCore.QMetaObject.connectSlotsByName(mapgui)

    def update_from_slider(self, slider_val):
        self.lineEdit.setText(str(self.mapping.dates[slider_val]))

    def update_date(self):
        self.mapping.update_date_by_idx(self.horizontalSlider.value())
        self.mapping.update_plot()

    def update_lat_lon(self, value):
        self.lineEdit_3.setText(str(value[1]))
        self.lineEdit_2.setText(str(value[0]))

    def retranslateUi(self, mapgui):
        _translate = QtCore.QCoreApplication.translate
        mapgui.setWindowTitle(_translate("mapgui", "Housing Prices"))
        self.label_2.setText(_translate("mapgui", self.mapping.dates[0]))
        self.label.setText(_translate("mapgui", self.mapping.dates[-1]))
        self.label_3.setText(_translate("mapgui", "Current Date: "))
        self.lineEdit.setText(str(self.mapping.cur_date))
        self.label_4.setText(_translate("mapgui", "Latitude | Longitude"))
        self.lineEdit_3.setText(str(self.mapping.center[1]))
        self.lineEdit_2.setText(str(self.mapping.center[0]))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mapgui = QtWidgets.QMainWindow()
    ui = Ui_mapgui()
    ui.setupUi(mapgui)
    mapgui.show()
    sys.exit(app.exec_())
